---
functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу
implicit:
  - Пользователь должен иметь возможность выбирать отображаемую в карточке товара валюту
  - Пользователь должен иметь возможность перехода на главную страницу при нажатии на логотип интернет-магазина
  - Пользователь должен иметь возможность обратиться в техническую поддержку интернет-магазина
  - При смене языка сайта описание товара в карточке должно изменяться в соответствии с выбранным языком
  - При входе на сайт должен открываться запрос на обработку файлов Cookie
  - Пользователь должен иметь возможность указывать количество товара, которое он хочет добавить в корзину
  - При добавлении товара в корзину в карточке товара должно отображаться количество товара в корзине пользователя
  - На сайте должны быть защищены все поля ввода пользовательских данных
  - Для оформления, оплаты и доставки заказа должны быть формы для записи контактных данных и способа оплаты
  - При переходе на следующую или предыдущую страницу каталог автоматически должен отображаться с первых позиций
